version: '3'
services:
  iot_server:
    build:
      context: "../"
      dockerfile: "docker/Dockerfile"
    ports:
      - "8100:8100"
    restart: "always"
    depends_on:
      - redis
      - mysql
    volumes:
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
    labels:
      author: "ycx"

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    restart: "always"
    volumes:
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
    labels:
      author: "ycx"

  mysql:
    image: "mysql:5.7"
    ports:
      - "3306:3306"
    volumes:
      - /root/docker_mysql/conf:/etc/mysql/conf.d
      - /root/docker_mysql/logs:/logs
      - /root/docker_mysql/data:/var/lib/mysql
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    restart: "always"
    labels:
      author: "ycx"